name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          run-test: false