name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
            
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"

      - name: Conan detect profile
        run: conan profile detect

      - name: Conan install dependencies
        run: conan install . --output-folder=${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build --preset conan-release

      - name: Build project
        run: cd ${{github.workspace}}/build && cmake --build .

      - name: Test project
        run: cd ${{github.workspace}}/build && ctest .